import { Nunito } from "next/font/google";
import "./global.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Uniart Troféus - Você sempre no topo!",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
